name: wofs_fcst_skill
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pip=21.2.4
  - scikit-learn=1.0.2
  - py-xgboost=1.3.3
  - pip:
      - numpy==1.20.2
      - pandas==1.4
      - matplotlib==3.5.1
      - pyarrow==11.0.0
      - xgboost==1.5.2
      - scikit-optimize==0.9.0
      - scikit-explain==0.0.4
      - imblearn
      - hyperopt==0.2.7
